# -*- coding: utf-8 -*-
"""module_testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/101WltDTJmn1hm_oYHsRoJ5utCXtHYHZI
"""

!git clone https://github.com/otroyobuoy/python_crash_couse.git

# Commented out IPython magic to ensure Python compatibility.
# %cd python_crash_couse

!git pull origin master

from python_crash_couse import pizza

pizza.make_pizza(16, "pepperoni")

from pizza import make_pizza

make_pizza(10, "pineapple")

from pizza import make_pizza as mp

mp(10, "pineapple")

import pizza as p

p.make_pizza(15,"guava")

from pizza import *

